
name: flutter_starter_mobile
description: APP_DESCRIPTION.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.0.1
  provider: ^6.0.0
  # dependency injection
  get_it: ^7.2.0
  # firebase
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  cloud_firestore: ^3.1.1
  firebase_crashlytics: ^2.0.7
  firebase_dynamic_links: ^2.0.9
  # auth
  google_sign_in: ^5.0.2 
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  # refresh
  pull_to_refresh: ^2.0.0
  # data management
  freezed_annotation:
  # formatting
  sprintf: ^6.0.0
  # styling
  ionicons: ^0.1.2
  # other
  internet_connection_checker: ^0.0.1+2
  stack_trace: ^1.10.0
  simple_logger: ^1.9.0


dev_dependencies:
  # tests
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  mockito: ^5.0.15
  # other
  build_runner: ^2.1.2
  json_serializable: ^6.1.3
  freezed: ^1.1.0
  flutter_lints: ^1.0.0
  rename: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  

flutter:

  uses-material-design: true

  # assets:
  #   # emojis
  #   - assets/images/emojis/heart_emoji.png

  # fonts:
  # - family: IBMPlexMono
  #   fonts:
  #     - asset: assets/fonts/IBMPlexMono-Thin.ttf
  #       weight: 100